version: '3.7'

services:
    php-fpm:
        container_name: laravel_comic
        build:
            context: .
            dockerfile: php/Dockerfile
        working_dir: /var/www
        volumes:
            - ../src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - app-networks
    nginx:
        container_name: comic_nginx
        build:
            context: .
            dockerfile: nginx/Dockerfile
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ../src:/var/www
        working_dir: /var/www
        ports:
            - 8000:80
        networks:
            - app-networks
    mysql:
        image: mysql:8.0
        container_name: db-comic
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: comic
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/sql:/docker-entrypoint-initdb.d
        networks:
            - app-networks
    phpmyadmin:
        container_name: comic_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db-comic
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "8088:80"
        networks:
            - app-networks
    mailcatcher:
        container_name: comic_mailcatcher
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025
        networks:
              - app-networks
networks:
    app-networks:
        driver: bridge
